import 'package:flangapp_app/enum/action_type.dart';
import 'package:flangapp_app/models/navigation_item.dart';

import '../enum/background_mode.dart';
import '../enum/load_indicator.dart';
import '../enum/template.dart';

class Config {

  /// Generated by SiteNative 31-01-2023 08:14:43
  /// App UID: 19a140bb-3208-371a-b1ec-1257ce8b3394
  /// Version: https://load81.flixshark.ga/backend/
  /// API server: {VERSION}

  /// *** App config *** ///
  // App name
  static String appName = "Vl Imoveis";
  // App link
  static String appLink = "https://vlimoveis.net/";
  // Display page name without app name (after 1 page)
  static bool displayTitle = true;
  // Main color (any HEX color)
  static String color = "#E91E63";
  // Active color (any HEX color)
  static String activeColor = "#E91E63";
  // Icon color color (any HEX color)
  static String iconColor = "#E91E63";
  // Title color (true - white, false - black)
  static bool isDark = true;
  // Pull to refresh enabled
  static bool pullToRefresh = true;
  // User agent
  static String userAgent = "";
  // Admin email
  static String appEmail = "kalleu323@gmail.com";
  // Template
  static Template appTemplate = Template.blank;
  // Loading indicator style
  static LoadIndicator indicator = LoadIndicator.none;
  // Loading indicator color
  static String indicatorColor = "#E91E63";

  /// *** Access ** ///
  // Access to camera
  static bool accessCamera = false;
  // Access to microphone
  static bool accessMicrophone = false;
  // Access to geolocation
  static bool accessLocation = false;

  /// *** Drawer settings *** ///
  // Title
  static String drawerTitle = "";
  // Subtitle
  static String drawerSubtitle = "";
  // Background mode
  static BackgroundMode drawerBackgroundMode = BackgroundMode.none;
  // Background color (any HEX color)
  static String drawerBackgroundColor = "#74072C";
  // Title color (true - white, false - black)
  static bool drawerIsDark = false;
  // Background image name
  static String drawerBackgroundImage = "drawer_background.png";
  // Logo image name
  static String drawerLogoImage = "logo.png";
  // Display logo
  static bool drawerIsDisplayLogo = false;

  /// *** Splashscreen settings *** ///
  // Background color (any HEX color)
  static String splashBackgroundColor = "#670D2B";
  // Text color (any HEX color)
  static String splashTextColor = "#000000";
  // Is image background
  static bool splashIsBackgroundImage = false;
  // Background image name
  static String splashBackgroundImage = "splash_screen.png";
  // Tagline
  static String splashTagline = "";
  // Delay display (seconds)
  static int splashDelay = 3;
  // Logo image name
  static String splashLogoImage = "splash_logo.png";
  // Display logo
  static bool splashIsDisplayLogo = true;

  /// *** PUSH OneSignal settings *** ///
  // App ID
  static String osAppID = "";
  // Signing
  static String osSigning = "471d9606df31bed26f5878a658ec5c7bf535aa627871c347480a4ba4d94585b9";
  // Enabled android?
  static bool osAndroidEnabled = false;

  /// *** Website styles *** ///
  // List div for hide in app
  static List<String> cssHideBlock = [];

  /// *** Localization *** ///
  // Name offline image
  static String offlineImage = "wifi.png";
  // Error internet connection (offline)
  static String messageErrorOffline = "Sem conexão com a internet";
  // Error open web page
  static String messageErrorBrowser = "Falha ao carregar a página. Por favor, tente novamente mais tarde!";
  // Name error page image
  static String errorBrowserImage = "error.png";
  // Title about exit from app (Android)
  static String titleExit = "Confirmar";
  // Message about exit from app (Android)
  static String messageExit = "Tem certeza de que deseja sair do aplicativo?";
  // Confirm button about
  static String actionYesDownload = "Sim";
  // Cancel button
  static String actionNoDownload = "Não";
  // Contact us email (About screen)
  static String contactBtn = "Contacte-nos com e-mail";
  // Back
  static String backBtn = "Volte";

  /// *** Navigation *** ///
  // Main app navigation
  static List<NavigationItem> mainNavigation = [
    	NavigationItem(name: "Imoveis",icon: "home.svg",type: ActionType.internal,value: "https://vlimoveis.net/imoveis/",),
	NavigationItem(name: "Inicio",icon: "caret-back.svg",type: ActionType.internal,value: "https://vlimoveis.net/",),
	NavigationItem(name: "entrar em contato",icon: "call-sharp.svg",type: ActionType.internal,value: "https://web.whatsapp.com/send?phone=61999876942&amp;text=Ol%C3%A1%20vim%20atrav%C3%A9s%20do%20site,%20gostaria%20de%20saber%20mais%20informa%C3%A7%C3%B5es.",),

  ];
  // Bar app navigation
  static List<NavigationItem> barNavigation = [
    
  ];
  // Modal navigation
  static List<NavigationItem> modalNavigation = [
    
  ];
}