import 'package:flangapp_app/enum/action_type.dart';
import 'package:flangapp_app/models/navigation_item.dart';

import '../enum/background_mode.dart';
import '../enum/load_indicator.dart';
import '../enum/template.dart';

class Config {

  /// Generated by SiteNative 21-12-2022 17:52:09
  /// App UID: 424064fd-83a6-bb37-a886-53a1854a21c8
  /// Version: https://load81.flixshark.ga/backend/
  /// API server: {VERSION}

  /// *** App config *** ///
  // App name
  static String appName = "FlixShark";
  // App link
  static String appLink = "https://flixshark.ga";
  // Display page name without app name (after 1 page)
  static bool displayTitle = true;
  // Main color (any HEX color)
  static String color = "#FFC107";
  // Active color (any HEX color)
  static String activeColor = "#FFC107";
  // Icon color color (any HEX color)
  static String iconColor = "#FFC107";
  // Title color (true - white, false - black)
  static bool isDark = true;
  // Pull to refresh enabled
  static bool pullToRefresh = true;
  // User agent
  static String userAgent = "";
  // Admin email
  static String appEmail = "load81@flixshark.ga";
  // Template
  static Template appTemplate = Template.drawer;
  // Loading indicator style
  static LoadIndicator indicator = LoadIndicator.none;
  // Loading indicator color
  static String indicatorColor = "#FFC107";

  /// *** Access ** ///
  // Access to camera
  static bool accessCamera = false;
  // Access to microphone
  static bool accessMicrophone = false;
  // Access to geolocation
  static bool accessLocation = false;

  /// *** Drawer settings *** ///
  // Title
  static String drawerTitle = "";
  // Subtitle
  static String drawerSubtitle = "";
  // Background mode
  static BackgroundMode drawerBackgroundMode = BackgroundMode.color;
  // Background color (any HEX color)
  static String drawerBackgroundColor = "#FFC107";
  // Title color (true - white, false - black)
  static bool drawerIsDark = true;
  // Background image name
  static String drawerBackgroundImage = "drawer_background.png";
  // Logo image name
  static String drawerLogoImage = "logo.png";
  // Display logo
  static bool drawerIsDisplayLogo = false;

  /// *** Splashscreen settings *** ///
  // Background color (any HEX color)
  static String splashBackgroundColor = "#0774FF";
  // Text color (any HEX color)
  static String splashTextColor = "#ffffff";
  // Is image background
  static bool splashIsBackgroundImage = false;
  // Background image name
  static String splashBackgroundImage = "splash_screen.png";
  // Tagline
  static String splashTagline = "";
  // Delay display (seconds)
  static int splashDelay = 3;
  // Logo image name
  static String splashLogoImage = "splash_logo.png";
  // Display logo
  static bool splashIsDisplayLogo = true;

  /// *** PUSH OneSignal settings *** ///
  // App ID
  static String osAppID = "";
  // Signing
  static String osSigning = "f0452e11fc21dc81ea03dac9f6d41d50fe48280852736af1358d9c7337d7c097";
  // Enabled android?
  static bool osAndroidEnabled = false;

  /// *** Website styles *** ///
  // List div for hide in app
  static List<String> cssHideBlock = [];

  /// *** Localization *** ///
  // Name offline image
  static String offlineImage = "wifi.png";
  // Error internet connection (offline)
  static String messageErrorOffline = "Poxa! Parece que você está no tempo das cavernas amigo! Check sua conexão e tente novamente!";
  // Error open web page
  static String messageErrorBrowser = "Humm! Estamos com dificuldade em abrir esta página!";
  // Name error page image
  static String errorBrowserImage = "error.png";
  // Title about exit from app (Android)
  static String titleExit = "Confirmação";
  // Message about exit from app (Android)
  static String messageExit = "Poxa! Já vai tão cedo? Quer mesmo sair do app? ";
  // Confirm button about
  static String actionYesDownload = "Sim";
  // Cancel button
  static String actionNoDownload = "Não";
  // Contact us email (About screen)
  static String contactBtn = "Fale Conosco!";
  // Back
  static String backBtn = "Voltar";

  /// *** Navigation *** ///
  // Main app navigation
  static List<NavigationItem> mainNavigation = [
    	NavigationItem(name: "Políticas de Privacidade",icon: "shield-checkmark-outline.svg",type: ActionType.internal,value: "https://flixshark.ga/page/politica-de-privacidade",),
	NavigationItem(name: "Termos de Uso",icon: "flag-outline.svg",type: ActionType.internal,value: "https://flixshark.ga/page/termos-de-uso",),
	NavigationItem(name: "Desenvolvedor",icon: "code-working-sharp.svg",type: ActionType.internal,value: "https://web.telegram.org/k/#@DrakenDev",),

  ];
  // Bar app navigation
  static List<NavigationItem> barNavigation = [
    	NavigationItem(name: "Inicio",icon: "home-outline.svg",type: ActionType.internal,value: "https://flixshark.ga",),
	NavigationItem(name: "Explorar",icon: "planet-outline.svg",type: ActionType.internal,value: "https://flixshark.ga/discovery",),
	NavigationItem(name: "Filmes",icon: "film-outline.svg",type: ActionType.internal,value: "https://flixshark.ga/movies",),
	NavigationItem(name: "Séries",icon: "tv-outline.svg",type: ActionType.internal,value: "https://flixshark.ga/series",),
	NavigationItem(name: "Gêneros",icon: "grid-outline.svg",type: ActionType.internal,value: "https://flixshark.ga/categories",),

  ];
  // Modal navigation
  static List<NavigationItem> modalNavigation = [
    
  ];
}